# docker-compose.yml
version: '3.9'

services:
  nextjs:
    container_name: nextjs_app
    build:
      context: .
      dockerfile: Dockerfile
      # target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Use the .env file for the MongoDB URI
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Mount the .env file into the container
    volumes:
      - .env:/app/.env