import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import { useSession } from "next-auth/react";
import image from "next/image";
import { TypeAnimation } from 'react-type-animation';


export default function Home() {

  const { data } = useSession();
  // console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Strength Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <TypeAnimation 
            style={{
              fontWeight: '550',
            }}
            cursor={true}
            sequence={[
              "Track Your Strength",
              5000,
              "Track Your Weight",
              5000,
              "Lift Beyond Limits",
              5000,
               "Empower Your Gains",
              5000,
            ]}
            speed={1}
            deletionSpeed={1}
            repeat={Infinity}
            className='typewriter_span'>
          </TypeAnimation>
        </h1>

        <p className={styles.description}>
          Get started by uploading your <Link className={styles.link} href="/showdata">lifting data!</Link>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2> <span><i class="bi bi-pencil-fill"></i></span> Progress Logging</h2>
            <p>Keep track of your weight lifting progress over time</p>
          </div>

          <div className={styles.card}>
            <h2><span><i class="bi bi-book"></i></span> Learn </h2>
            <p>Explore additional exercises and routines to help you on your journey</p>
          </div>

          <div className={styles.card}>
            <h2> <span><i class="bi bi-bar-chart-fill"></i> </span>Visualize</h2>
            <p>Visualize your weight lifting progress through various charts </p>
          </div>
        </div>

        <div className={styles.info}>
        <h2>We&apos;ll help you track your progress and optimize your workouts based on your input and your favorite routines.</h2>
        </div>

        <div className={`card bg-light ${styles.imageContainer}`}>
          <img src="/deadlift.jpeg" className={styles.imageFit}>

          </img>
        </div>

        <div className={styles.info}>
        <h2>Data visualization, made easy for you</h2>
        </div>

        {/* only render this if the user is not logged in */}
        {data === null && (
          <div className={styles.info}>
          <h1>Want to get started now?</h1>
          <h3> Register now and get started! </h3>
          <Link href="/register" class="btn btn-primary"> Register </Link>
          </div>
        )}

      </main>

      <footer className={styles.footer}>
          Created by Jaskaranpal Singh
      </footer>
    </div>
  )
}
